[package]
name = "api_holder_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
diesel-derive-enum = "2.1.0"
lazy_static = "1.5.0"
dotenv = "0.15.0"