name: API holder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Rust (Actix-web) Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api_holder_backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api_holder_backend/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('api_holder_backend/Cargo.lock') }}

      - name: Run Rust tests
        run: cargo test --all
